- hosts: nodes
  become: yes # To become sudo user
  tasks:
  - name: install python3-simplejson
    apt:
      name: python3
      state: latest
      update_cache: yes

  - name: ensure docker is installed
    apt:
      name: docker.io
      state: latest
      update_cache: yes
      
  - name: ensure docker-compose is installed
    apt:
      name: docker-compose-v2
      state: latest
      update_cache: yes

  - name: Added user to docker group
    user:
      name: vagrant
      groups: docker
      append: yes
